In [ ]:
# Assignment: NumPy Arrays and Functions
# Ranode Krishana vilas
#Roll No: 158
#
import numpy as np

In [2]:
# -----------------------------------------------------------
# Q1. Basic Array Creation
# -----------------------------------------------------------

# 1D Array
arr1 = np.arange(10)
print("1D Array:", arr1)

# 2D Array (3x3)
arr2 = np.arange(1, 10).reshape(3, 3)
print("\n2D Array:\n", arr2)

# 3D Array (2x3x4) with random integers
arr3 = np.random.randint(10, 50, (2, 3, 4))
print("\n3D Array:\n", arr3)

1D Array: [0 1 2 3 4 5 6 7 8 9]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
 [[[28 32 20 20]
  [33 45 49 33]
  [12 31 11 33]]

 [[39 47 11 30]
  [42 21 31 34]
  [36 37 25 24]]]


In [3]:
# -----------------------------------------------------------
# Q2. Array Attributes
# -----------------------------------------------------------

print("\nArray Attributes of arr2:")
print("Shape:", arr2.shape)
print("Dimension:", arr2.ndim)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)


Array Attributes of arr2:
Shape: (3, 3)
Dimension: 2
Size: 9
Data Type: int64


In [4]:
# -----------------------------------------------------------
# Q3. Indexing & Slicing
# -----------------------------------------------------------

a = np.array([10, 20, 30, 40, 50])
print("\nFirst 3 elements:", a[:3])

b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Second row:", b[1])
print("Last column:", b[:, -1])



First 3 elements: [10 20 30]
Second row: [4 5 6]
Last column: [3 6 9]


In [5]:
# -----------------------------------------------------------
# Q4. Mathematical Operations
# -----------------------------------------------------------

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

print("Square Root:", np.sqrt(a))
print("Exponential:", np.exp(a))
print("Sine:", np.sin(a))


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Square Root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Sine: [0.84147098 0.90929743 0.14112001]


In [6]:
# -----------------------------------------------------------
# Q5. Array Functions
# -----------------------------------------------------------

print("\nEven numbers 2-20:", np.arange(2, 21, 2))
print("10 evenly spaced numbers 0-1:", np.linspace(0, 1, 10))
print("Identity Matrix:\n", np.eye(4))


Even numbers 2-20: [ 2  4  6  8 10 12 14 16 18 20]
10 evenly spaced numbers 0-1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
# -----------------------------------------------------------
# Q6. Aggregate Functions
# -----------------------------------------------------------

arr = np.array([10, 20, 30, 40, 50])
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Max value:", np.max(arr), "at index", np.argmax(arr))
print("Min value:", np.min(arr), "at index", np.argmin(arr))



Sum: 150
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
Max value: 50 at index 4
Min value: 10 at index 0


In [8]:
# -----------------------------------------------------------
# Q7. Reshaping & Flattening
# -----------------------------------------------------------

arr = np.arange(1, 13)
reshaped = arr.reshape(3, 4)
print("\nReshaped 3x4:\n", reshaped)
print("Flattened:", reshaped.flatten())


Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
# -----------------------------------------------------------
# Q8. Stacking
# -----------------------------------------------------------

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("\nVertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [10]:
# -----------------------------------------------------------
# Q9. Random Numbers
# -----------------------------------------------------------

print("\n5 Random floats between 0 and 1:", np.random.rand(5))
print("4x4 Random integers 1-100:\n", np.random.randint(1, 101, (4, 4)))

np.random.seed(42)
print("Reproducible Random Numbers:", np.random.rand(5))


5 Random floats between 0 and 1: [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457]
4x4 Random integers 1-100:
 [[ 3 51  7 21]
 [73 39 18  4]
 [89 60 14  9]
 [90 53  2 84]]
Reproducible Random Numbers: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [12]:
# -----------------------------------------------------------
# Q10. Application-Based
# -----------------------------------------------------------

# Euclidean Distance
p1 = np.array([3, 4])
p2 = np.array([0, 0])
dist = np.linalg.norm(p1 - p2)
print("\nEuclidean Distance:", dist)

# Normalize Array
arr = np.array([1, 2, 3, 4, 5])
normalized = arr / np.sum(arr)
print("Normalized Array:", normalized)

# Top 3 Scores
marks = np.array([56, 89, 74, 92, 67, 85])
top3 = np.sort(marks)[-3:][::-1]
print("Top 3 Scores:", top3)



Euclidean Distance: 5.0
Normalized Array: [0.06666667 0.13333333 0.2        0.26666667 0.33333333]
Top 3 Scores: [92 89 85]
